name: Test Build Assets
on:
  push:
    branches: 
      - velocity_potential_over_cylinder
  pull_request: 
    branches: 
      - velocity_potential_over_cylinder

env:
  WINDOWS_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/a37c30c3-a846-4371-a85d-603e9a9eb94c/intel-oneapi-hpc-toolkit-2025.0.1.48_offline.exe
  WINDOWS_FORTRAN_COMPONENTS: intel.oneapi.win.ifort-compiler
  LINUX_FORTRAN_COMPONENTS: intel-oneapi-compiler-fortran

jobs:
  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Setup | Checkout repository at workflow sha
        uses: actions/checkout@v4
      - name: Setup | Setup apt repo
        run: .github/scripts/setup_apt_repo_linux.sh
      - name: Cache | Collect versioned dependencies of apt packages
        run: .github/scripts/apt_depends.sh $LINUX_FORTRAN_COMPONENTS | tee depends.txt
      - name: Cache | Install
        id: cache-install
        uses: actions/cache@v3
        with:
          path: |
            /opt/intel/oneapi/compiler
          key: install-${{ env.LINUX_FORTRAN_COMPONENTS }}-${{ hashFiles('**/depends.txt') }}-compiler-${{ hashFiles('**/.github/scripts/cache_exclude_linux.sh') }}
      - name: Intel Fortran Install
        if: steps.cache-install.outputs.cache-hit != 'true'
        run: .github/scripts/install_linux_apt.sh $LINUX_FORTRAN_COMPONENTS
      - name: Build
        run: .github/scripts/build_linux.sh
      - name: Tar files
        run: tar -cvf nemoh.tar bin
      - uses: actions/upload-artifact@v4
        with:
          name: nemoh-linux
          path: nemoh.tar
      - name: Exclude unused files from cache
        if: steps.cache-install.outputs.cache-hit != 'true'
        run: .github/scripts/cache_exclude_linux.sh

  linux-test:
    needs: linux
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: nemoh-linux
      - name: Untar files
        run: tar -xf nemoh.tar
      - name: Test
        run: |
          $GITHUB_WORKSPACE/bin/preProc
          $GITHUB_WORKSPACE/bin/solver
          $GITHUB_WORKSPACE/bin/postProc
        working-directory: ./Examples/InteractingCube

  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Setup | Checkout repository at workflow sha
        uses: actions/checkout@v4
      - name: Intel Fortran Install
        run: .github/scripts/install_windows.bat $WINDOWS_HPCKIT_URL $WINDOWS_FORTRAN_COMPONENTS
      - name: Build
        run: .github/scripts/build_windows.bat
      - uses: actions/upload-artifact@v4
        with:
          name: nemoh-win64
          path: x64

  windows-test:
    needs: windows
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: nemoh-win64
          path: x64
      - name: Test
        run: |
          $GITHUB_WORKSPACE/x64/Release/preProcessor.exe
          $GITHUB_WORKSPACE/x64/Release/Solver.exe
          $GITHUB_WORKSPACE/x64/Release/postProcessor.exe
        working-directory: ./Examples/InteractingCube
